### ISSUE TITLE
Rock crystal ore does not drop a rock crystal when mined with a Pickaxvel

### ISSUE THREAD

**Issue by Pandemoneus** [davqvist/Exoria#155]
Using a diamond pickaxe works.

**Comment by davqvist** [comment]
Yeah, that is a tough one, that I am aware of. Both mods do some "hacky" stuff. Astral Sorcery has some code that prevents them to be mined by anything but a player. And the Flexible Tools act like a quarry if I understood correctly. So this is kinda expected behaviour. Any advice on how to solve that is appreciated.

**Comment by hron84** [comment]
@HellFirePVP is there a way to register a tool as a valid Rock Crystal mining tool?

**Comment by HellFirePvP** [comment]
> And the Flexible Tools act like a quarry if I understood correctly

If that's the case then it's due to their implementation problematic. I won't change this on my end as i won't be able to check/capture whatever "player" is trying to mine the ore with as that would open up possibilities to circumvent the quarry-protection.

**Comment by SephirothWS** [comment]
What's the point of quarry-protection anyways?

**Comment by HellFirePvP** [comment]
You already named it. To prevent the ore from being quarry-able. I want the player to do stuff and not to have him play GUI-simulator.

**Comment by hron84** [comment]
@MrRiegel can you help us?

**Comment by KidsDontPlay** [comment]
I can.
@HellFirePvP why do you use `Block.harvesters`? It's meant forge internal only.
I can modify it to make my tools able to mine rock crystals but that's pretty hacky.
I don't want to break your quarry-protection, just enable normal mining.

**Comment by HellFirePvP** [comment]
I wonder why you chose to 'break them like a quarry' instead of behaving like a normal tool.
I use that cause it's set during the normal block-breaking routine and otherwise there is no way getting the player trying to break the block in the getDrops besides passing a static reference around which isn't great either. If it's supposed to be forge internal only or not is none of my concern here. It does what i need it for and there is no gain in implementing something a 2nd time which is already implemented and accessible AND hooked into the proper places.

**Comment by KidsDontPlay** [comment]
`harvestBlock()` drops the items right on the ground. But that's not what I want everytime. there is an upgrade that transfers dropped items directly into an inventory.

Edit: I understand your way to prevents 'quarries'. I guess it's the only way to do (a `HarvestDropsEvent` with highest priority for your own block may work too).
I am gonna modify `harvesters` to make my mod compatible

**Comment by KidsDontPlay** [comment]
ok guys. i fixed it. you need the new limelib version

**Comment by hron84** [comment]
@MrRiegel technically, you can catch the dropped item similarly as TiCon or other tools with "Magnetic" trait do - pick up from the ground. Since you technically just teleport the dropped item to an inventory... whether it's player inventory or a chest it does not matter.
