### ISSUE TITLE
Nutrition food values

### ISSUE THREAD

**Issue by redcatone** [davqvist/Exoria#161]
Terraqueous coconuts and life fruit don't have any nutrition values.

Vanilla cookies seem vastly superior to other methods of fat early game. 2 wheat + 1 cocoa bean = 8 cookies (0.9% carbs and fat, total = 7.2%). Other options need much more resources such as XL Food Mod needing 9 cocoa beans for just 1 piece of chocolate (0.4% carbs and fat). Most of the chocolate based foods are vastly under-powered compared to normal cookies.

I recommend either nerfing the amount of cookies you get per craft/reduce its nutrition value and/or buffing the other chocolate based foods.

**Comment by davqvist** [comment]
Added Coconuts and Life Fruit in 0.4.3

I am not too worried about Cookies being overpowered, also there are also Donuts for good Fat source. It is more that Chocolate is underpowered, but there is not a lot I can do because if I change the Chocolate recipe, then the Chocolate Pie is quite powerful.
