### ISSUE TITLE
Formation Wand doesnt work with Chiselled stuff

### ISSUE THREAD

**Issue by zOwenn** [davqvist/Exoria#219]
Formation wand defaults to the chiselled brick variants of things when trying to build with chiselled basalt & cobblestone

**Comment by redcatone** [comment]
Issue with [Astral Sorcery 1.8.10](https://github.com/HellFirePvP/AstralSorcery/issues/692). In the beta we were using the Astral Sorcery 1.9 beta which didn't have this problem, but it was since taken off curseforge and is set to release later. Currently the wand doesn't differentiate between the metadata of blocks.

**Comment by davqvist** [comment]
Issue seems to be resolved since a while
