### ISSUE TITLE
AE2 Grindstone can grind down metal apparently

### ISSUE THREAD

**Issue by zOwenn** [davqvist/Exoria#235]
Havent tried myself but someone pointed out that the recipes for grinding down tin and copper in the AE2 Grindstone is apparently enabled - sort of kills the need for the mixer centrifuge for bronze - and i *think* this is unintentional

**Comment by MorganSimic** [comment]
I mentioned that in the Discord. The problem is not that you can grind metals but that you can craft the alloy blends i guess. Crafting the blends makes the alloy kiln useless for alloying as well as the embers setup bypassing them alltogether. But on a second tought the ability to grind metals in the grindstone makes the metal atomizer somewhat useless. 
Tl;dr: You can craft alloy blends wich makes the alloy gating pointless.

**Comment by zOwenn** [comment]
I made this issue prior to the talk in discord - and know its main problem is alloy blend & pretty sure its been noted down now

**Comment by davqvist** [comment]
Blends will be uncraftable in 1.1.0
