### ISSUE TITLE
Creating glass in the latest update appears to be broken

### ISSUE THREAD

**Issue by notWaterGuy12** [davqvist/Exoria#293]
Went to cast some glass in the latest update and it refuses to cast. Correct cast is being used, most likely a recipe issue. Using the foundry with the metal caster to create the glass.

**Comment by gekkobear** [comment]
It let me melt the glass, it let me pour the glass... But, like you, the metal caster refuses to cast it.

Jumping into creative to get some more info:
Does the Block Casting table cast work instead of the metal caster for glass blocks? Yes
Will the Metal Caster cast other things (ingots, gears, etc.)? Yes
Metal Caster can be Redstone driven, would a level help, or a button? No
Metal Casting table has an RF bar, would RF help? No
Can you put a faucet on the Metal Caster to pour out of it into a Block Casting table? yes

Tells me how to melt glass and move forward; but not why it won't work in the Metal Caster.

If I had to guess, the Metal Caster, Liquid Glass, Basin says it'll make minecraft glass.
It also says it'll make TiC Clear Glass the exact same way, with the same materials, causing a dupe.

The Block Casting Table only has (and makes) the TiC Clear Glass recipe, so that one works.
Maybe?

**Comment by davqvist** [comment]
Huh, I haven't changed anything, but I can replicate this. This will be tricky to figure out.

**Comment by bsulcer** [comment]
I'm seeing a similar problem with casting iron rods.  Caster full of liquid iron, rod mold in place, but it won't cast.  Ingot and plate molds work fine in the caster, and the rod casting table works as well.

**Comment by bsulcer** [comment]
A further data point: the caster won't cast liquid steel into any of the revolver part molds.

**Comment by notWaterGuy12** [comment]
When starting up a world i just recently noticed that it displays "WARNING: Casting recipe not found" twice.  Could this be the source of the issue?

**Comment by davqvist** [comment]
Will be fixed in 1.2.1
Mod update fixed it
