### ISSUE TITLE
Magical burnium dust disappearing.

### ISSUE THREAD

**Issue by UMTTEPATOP** [davqvist/Exoria#304]
When i tried to make Burnium crystal (it calls "Burnium") with burnium dust and liquid crystal with condenser, i spent like 4 burnium dusts into nothing. And there were no "ding" sound, burnium crystals wasn`t appeared even after reconnecting to the world. Interesting thing that only burnium dust was disappearing, liquid crystal stayed on its place.
Thank you.

**Comment by davqvist** [comment]
I need a screenshot of your setup. Are you sure it is not pulled out with a hopper or pipe?

**Comment by redcatone** [comment]
Maybe related to https://github.com/davqvist/Exoria/issues/172?

**Comment by McFrugal** [comment]
It might be that you don't have enough efficiency to make a crystal from one dust.  At 100% efficiency/speed it gives about 75% of a crystal, but the progress is completely lost when it runs out of ingredients.  With a stone condenser you have 80% efficiency and 100% speed, so that's 80% multiplied together.  Anything without a base conversion ratio of at least 1.0 will give you nothing if you insert dust one at a time, you have to put in more than one.

Upgrade your condenser and the casing for your condenser ASAP.  Your combustion chamber doesn't need an upgrade since it's only used for making glass shards.

#172 looks like it was related to using a filtered hopper or something under the condenser, don't do that.  Just put a chest under it, it'll output automatically.

**Comment by UMTTEPATOP** [comment]
@McFrugal Thank You <3
