### ISSUE TITLE
You can go to overworld in early game.

### ISSUE THREAD

**Issue by 10v01** [davqvist/Exoria#333]
Just build a misty world portal in exoria, get into the misty world, and then build a new portal in misty world. Then you can get back to overworld through the new portal.

**Comment by davqvist** [comment]
Known. Nothing I can do about it atm

**Comment by McFrugal** [comment]
Well, you could put a restriction on the portal blocks so they can only be placed in Exoria, just like that advanced crafting table thing.

**Comment by davqvist** [comment]
Good idea, will do this in 1.3.0

**Comment by 10v01** [comment]
Nope.
You should restrict the gold block.
A piston can disable the portal.
Just disable the portal and lit it again. You will be able to go to overworld.

**Comment by McFrugal** [comment]
Oh, the return portal can do that, you don't even need to construct new portal blocks?  Sheesh, that is a problem.

**Comment by Trinsdar** [comment]
@davqvist the issue is not solved; you can still go to the overworld using a piston to disable the portal by pushing into the middle block and then you can place a gold block down to relight it. then if you warp home via warpstones you can reenter the portal on that side to create another portal in the mistyworld going back to exoria. I recommend to do what 10v01 said. I can upload a video later if need be.

**Comment by davqvist** [comment]
I know that you can do that, but if you do that, you want to cheat anyway and then I don't care. I only want to prevent accidental cheating.
